### PR TITLE
Fix changing source

### PR DESCRIPTION
**Pull request by rpaaron**
Fixes https://github.com/traviscross/mtr/issues/378

I moved the "starting a new traceroute" part of `net_reopen` to it single caller in `gtk.c`
Then moved the common parts of `net_open` to `net_reopen` including the initialisation of the source addresses, and now call `net_reopen` from `net_open`

### CODE REVIEW

**Review by robert-scheck — COMMENTED** [review]
I am sorry, but this patch is incomplete: Running `mtr -g ::1` and then switching to `8.8.8.8` in the GUI does *not* work, but aborts with `mtr: Address not available`

**Comment by rewolff** [comment]
Yeah.... work needs to be done to be able to switch address families, right?

**Comment by robert-scheck** [comment]
Exactly!

**Comment by rewolff** [comment]
The annoying thing is that starting without a target and then specifying the target in the gui is a way to work with mtr, but if it chooses the AF wrong with the default target that would be annoying.

**Comment by robert-scheck** [comment]
No default target/destination leads to `AF_INET6` on most systems, because localhost resolves to ::1. But as the GUI allows to switch the target/destination (while the TUI doesn't), the address family needs to be re-evaluated with each target/destination change.

**Pull request merged**
