### PR TITLE
report: json: reworked with libjansson

### PR DESCRIPTION
**Pull request by ltWolfik**
I reworked JSON report to use libjansson. Consider such solution more robust.
I noticed that fixes JSON output when no hosts:
<details>
  <summary>Screenshot with comparison</summary>
  drawing
</details>
Also, it changes the following:

- report.mtr.{tests, tos} now output as number;
- report.hubs[].count now output as number;
- the precision of real numbers differs;

<details>
  <summary>Screenshot with comparison</summary>
  drawing
</details>

### CODE REVIEW

**Comment by rewolff** [comment]
What happens if libjansson isn't installed?

**Comment by ltWolfik** [comment]
I supposed libjansson should be mandatory dependence. But if it's critical - do it conditional dependence (like gtk and ncurses)?

**Comment by rewolff** [comment]
Yeah. I would prefer to keep things in line with other output modules: If the library for that feature is not available, that feature won't be built.

**Comment by ltWolfik** [comment]
I did Jansson to be optional dependence. Can you accept the PR?

**Pull request merged**
