### PR TITLE
Fix/raw dns

### LINKED ISSUE #309: dnsline in raw output shows only ip address
the raw output, outputs the dnsline before the hostname as been resolved.  Looks like this behaviour was introduced in 02a9e6193e5dec01198f7824b7ed92f320b4e7a9

### PR DESCRIPTION
**Pull request by krisl**
output dnsline only if hostname is resolved
fixes #309

### CODE REVIEW

**Comment by krisl** [comment]
@rewolff can I get some feedback on this PR please
Without this change, the raw mode never outputs a dnsline with a hostname, always just an ip address.

you can see an example in the raw output here https://github.com/traviscross/mtr/issues/308#issuecomment-515730925
every `h` line is followed by an identical, unresolved `d` line

**Comment by rewolff** [comment]
The original idea was to have the low-level stuff do the translation: so we have  a 4-byte integer and the low level stuff converts that to something printable. Either 8.8.8.8 or dns3.google.com, depending on the state of the resolver and the options specified. That makes the higher level code simpler: Simply call the conversion routine and display the results unquestioned. So that's why I don't like the 
 "check-for-null and do something else if that happens".   

Your change never implements the check-for-null that I expected to see. Why isn't it necessary?

**Comment by krisl** [comment]
I modified the function `dns_lookup2`.  There are two callers of it.  One from `dns_lookup` and the other from `raw_rawping`.
The problem is that at the time that `raw_rawping` is called, the dns resolution has not completed, so will always return just the ip address.
`raw_rawping` already has "check-for-null and do something else if that happens" logic, so I added similar logic to the other caller and allowed the function to return NULL.

The main issue being that the callers dont know when the name is resolved.  It looks like they rely on calling this function until something good comes out of it, essentially its polled.  I think the "right fix" here is to have the code output the resolved name at the time that it happens, and I have another branch that im working on to do that, but its a bigger job and i'd like to get much more discussion about it first.

At this time, its just broken.  It never resolves the name.  And this is the simplest change that I could think of to address the issue.  It only alters the behaviour for the one caller - raw mode.  And the other is preserved by moving the logic to that caller (the ternary function)

**Comment by rewolff** [comment]
Thanks for the explanation.

**Pull request merged**
