### PR TITLE
Gtk3

### PR DESCRIPTION
**Pull request by krisl**
addresses #314

### CODE REVIEW

**Comment by rewolff** [comment]
Hi, It looks nice and simple: Good! 
I have one worry. And that's that some corner where MTR used to compile now suddenly won't because the platform has GTK2 and not 3. This could be something like "macos" or "linux-environment on windows", where a big vendor demonstrates: "look you can compile a linux application" by compiling the one application that they worked on and then call it quits. 

The "G_OBJECT" vs "GTK_OBJECT" would easily be fixed: 
```
#if COMPILING_FOR_GTK2
#define G__OBJECT GTK_OBJECT
#else 
#define G__OBJECT G_OBJECT
#endif 
```
and this somewhere in a header. The actual code looks almost the same (no ugly #ifdefs inside the actual code). But some of the others would be more difficult. 

What do you think? Is this an issue? Can we drop GTK2 support just like that?

**Comment by krisl** [comment]
@rewolff  Cool, thanks

Those first two commits are valid even for GTK2, I can make a separate PR if you like?

And the third commit will then switch to using GTK3, but with warnings.  The next three commits just fix the warnings.
So one possibility would be just to allow GTK3 to be compiled with warnings.  Maybe you want a different `configure` option for that, eg `--with-gtk2` vs `--with-gtk3`?  or just to use the highest version found.

Does anyone know of other projects that support multiple GTK versions?

More than that, idk.  I suppose we can expect later versions only to diverge further.  What is the policy for supporting which gui frameworks?  We could make separate GTK2 and GTK3 versions of functions for where they differ significantly.  Or ultimately different files altogether.

I suppose the easiest thing to do, is for those platforms where GTK3 is not available (do such environments exist?), then they no longer will be complied with GTK support.

**Comment by rewolff** [comment]
No separate pull request required for now. First think about it for a second. And I'm thinking aloud in the hopes of getting feedback for when I think/say stupid things. 

If the differences are in compilation warnings or stuff like that, then I'd prefer GTK3 to be warning-less and leave those warnings for those who have to work with gtk2. 

Can I force a compilation with "only gtk2"? I have a machine that is quietly chugging along on ubuntu 14.04 but alas it doesn't have gtk at all. And just apt-get installing it won't work anymore.

**Comment by krisl** [comment]
how about this approach instead? https://github.com/traviscross/mtr/pull/318

@rewolff I'm not quite following what you said about "only gtk2".  If gtk isn't found at all, then it will just build without it. no?

**Comment by rewolff** [comment]
I have a relatively recent raspberry running somewhere. I explicitly installed libgtk-2.0-dev. I cloned the public repo, compiled and it works with Gtk support. Then after pulling your patch, I get "gtk     :no" detected in configure. 

I then reversed the "gtk-3.0 required" in configure.ac and I get two compile errors. Changing the "box new" to hbox_new and vbox_new as seemed to be required on the "orientation" argument and removing the call to gtk_menu_popup_at_pointer, I get a working, but ugly mtr. 
The ugly might be my guessing wrong for hbox/vbox. 

I'd say that keeping gtk2 compatiblity is doable. The configuration asks for "at least 2.0" will probably default to 3.0 when available. And a simple header that defines  gtk_hbox_new and gtk_vbox_new as gtk_box_new for gtk3 ONLY and for all I care it defines gtk_menu_popup_at_pointer as "nothing", then we have this working on both versions. 
If it is tons of work I'd say leave it, but it seems easy enough. 
Note that my code-style preference is to have the code READ as if it is written for the latest stuff, but with the hbox/vbox stuff we have to compromise: the compatiblity defines are easyest when we just keep the old code but insert a define to rewrite it on the fly for the new GTK.

**Comment by krisl** [comment]
cool, thanks for the explanation.
closing as the gtk3 with fallback to gtk2 branch is merged #318

**Pull request closed without merging**
