### PR TITLE
allow udp traceroute with fixed source and destination ports

### PR DESCRIPTION
**Pull request by russor**
I broke this out as separate pieces, but they're all mostly related.

### CODE REVIEW

**Comment by russor** [comment]
Actually, I'm not quite sure about the checksum calculations here.  I just noticed a compiler warning about type-punning in my fix for odd sized packets, and I'm not sure if this will be correct on big-endian systems; I'll try to setup a qemu vm with a big-endian architecture to verify / fix.

**Comment by russor** [comment]
This is better now.  Tested to make sure outgoing udp packets have correct checksum when sent from mac os x on intel, linux on mips64 (malta) via qemu, linux on intel, freebsd on intel, linux on armv5tel.

**Comment by rewolff** [comment]
Hi Russor, 
When I get the Email about a pull request, I sometimes defer responding  or looking into it to later on. And then I forget. So you having to  remind me is a result of that.

**Comment by aquerubin** [comment]
On Fri, 29 Apr 2016, rewolff wrote:

> Merged #110.

Lines 1582 and 1587 of net.c should be changed:

s/AF_INET/af/


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by russor** [comment]
rewolff -- no problem, i do the same thing all the time :)
AQ -- thanks for that fix

**Comment by aquerubin** [comment]
Russor can you submit a PR for that fix?  Afterwards I want to resubmit a PR to merge master into newdns as it's missing some of the latest updates.

**Comment by rewolff** [comment]
@aquerubin I just went ahead and pulled the latest sources, edited your fix and pushed it again. That should put your fix in the mainline, shouldn't it? Did I do that wrong?

**Comment by aquerubin** [comment]
On Sat, 30 Apr 2016, rewolff wrote:

> @aquerubin I just went ahead and pulled the latest sources, edited your 
> fix and pushed it again. That should put your fix in the mainline, 
> shouldn't it? Did I do that wrong?

That's fine.  What I was referring to is that some patches are being 
applied to master and some to newdns and they've gotten out of sync. The 
branches should be identical except for the resolver bits in dns.c.

I'd submitted a PR earlier to sync up newdns with the changes in master 
(PR #87) but it's outdated at this point so I'm gonna pull it and resubmit 
a new PR.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Pull request merged**
