### PR TITLE
2016 08 17 regression fixes and warnings removal

### PR DESCRIPTION
**Pull request by kerolasa**
Sorry about bit of a mess with autotools revamp. Here are fixes to mine and others regressions. In same go some warnings got to be removed.

### CODE REVIEW

**Comment by aquerubin** [comment]
On Wed, 17 Aug 2016, Sami Kerola wrote:

> Sorry about bit of a mess with autotools revamp. Here are fixes to mine 
> and others regressions. In same go some warnings got to be removed. You 
> can view, comment on, or merge this pull request online at:
>
>  https://github.com/traviscross/mtr/pull/138
>
> -- Commit Summary --
>
>  * warnigns: add void to functions that do not take any arguments
>  * build-sys: fix --without-ipinfo regressions
>  * build-sys: fix ./configure --disable-ipv6
>  * warnings: fix --disable-ipv6 --without-ipinfo compilation warnings
>
> -- File Changes --
>
>    M configure.ac (4)
>    M curses.c (2)
>    M dns.c (10)
>    M net.c (28)
>    M report.c (2)
>
> -- Patch Links --
>
> https://github.com/traviscross/mtr/pull/138.patch
> https://github.com/traviscross/mtr/pull/138.diff~.

In the interest of simplifying the codebase, I think all this effort to 
disable IPv6 at build-time should be redirected to detecting whether IPv6 
is enabled/useable at run-time and then doing the right thing.  I suspect 
there are few if any current POSIX-compliant environments that don't have 
support for the API functions that specifically provide IPv6 capability.

Many of the problems we've had in the past with IPv6 had more to do with 
the custom resolver code failing when IPv6 is either not configured or 
explicitly disabled in the OS.  But that part of the code is now legacy.

Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by rewolff** [comment]
Antonio, I agree that "detecting not-working IPV6 at turntime" should work. On the other hand, I don't want to lose compile-ability on systems that don't have the interface.

**Comment by rewolff** [comment]
kerolasa, I'm going to do the UNUSED things a bit different. I'm going to pull and then fix a few of your UNUSED things another way... I'm not sure if my compiler supports the unused keyword, so I'm not sure if I will see the difference.

**Comment by rewolff** [comment]
kerolasa, it seems that you put the "UNUSED" after the declaration of the argument: 
`void somefunc (int arg UNUSED)
`
while other places have the UNUSED before the argument: 
`void somefunc (UNUSED int arg)
`
I take it both are allowed, it seems I'm not getting any errors/warnings.

**Comment by aquerubin** [comment]
On Wed, 17 Aug 2016, rewolff wrote:

> Antonio, I agree that "detecting not-working IPV6 at turntime" should 
> work. On the other hand, I don't want to lose compile-ability on systems 
> that don't have the interface.

I fully support maintaining compile-ability but my question though is what 
reasonably current systems do NOT support the API?  Ie. it doesn't make 
sense to sprinkle the code with a bunch of ifdefs for code that would not 
cause a build error on a current system or even one that's 10+ years old. 
If you do find such an old system, I would then claim there are probably 
other far more important issues with the continued use of that OS than the 
ability to rebuild the latest and greatest version of mtr for it.  Sure 
you may need ifdefs for some of the actual code as a substitute for lack 
of runtime logic but for things like variable declarations do you really 
think it's necessarry?


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by rewolff** [comment]
I dislike the ifdefs... I would like them outside the main code path. 
for example: 
```
#ifdef ENABLE_IPV6
  struct sockaddr_storage name_struct;
#else
  struct sockaddr_in name_struct;
#endif
```
This should have been fixed with a
```
#ifdef ENABLE_IPV6
#define mtr_sockaddr_storage sockaddr_storage
#else
#define mtr_sockaddr_storage sockaddr_in
#endif
```
but in net.c there is lots of code "extra" for ipv6. If we can make that compile into "do nothing" code at compiletime under an `#ifndef ENABLE_IPV6` then that would clean things up a lot.

**Pull request merged**
